# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
chunkCpp <- function(x, chunkSize, overlap) {
    .Call(`_khermisc_chunkCpp`, x, chunkSize, overlap)
}

#' @export
rowMaxCpp <- function(x) {
    .Call(`_khermisc_rowMaxCpp`, x)
}

